name: Await Statuses
description: Wait for statuses on a given ref
author: Freckle
inputs:
  ref:
    description: |
      The ref to poll status checks on. If not specified, the head branch will
      be used for PR events and github.sha otherwise.
    required: false
  statuses:
    description: |
      A newline-separated list of status names to wait for. The Action will loop
      until all statuses are successful (or attempts are exhausted). If any
      statuses are failed, the Action will immediately fail.
    required: true
  poll-seconds:
    description: |
      Number of seconds to wait when polling current statuses. Default is 5.
    required: true
    default: 5
  poll-limit:
    description: |
      Give up after polling this many times. The default is 1440, which works
      out to 2 hours total with the default poll-seconds.
    required: true
    default: 1440
  format:
    description: |
      How to output as we poll. Print state of every status (rich) or emit a
      single dot (brief). Default is rich.
    required: true
    default: rich
  github-token:
    description: "Override GitHub token, if necessary"
    required: true
    default: "${{ github.token }}"
outputs:
  succeeded-statuses:
    description: Comma-separated list of succeeded statuses at step completion
  pending-statuses:
    description: Comma-separated list of pending statuses at step completion
  failed-statuses:
    description: Comma-separated list of failed statuses at step completion
runs:
  using: "node20"
  main: "dist/index.js"
